# Auto-generated using compose2nix v0.3.1.
{
  pkgs,
  lib,
  ...
}: {
  # Containers
  virtualisation.oci-containers.containers."solviadev-web" = {
    image = "ghcr.io/valnyx17/www-nginx:latest";
    labels = {
      "traefik.http.routers.solviadev.rule" = "Host(`solvia.dev`) || Host(`www.solvia.dev`)";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=web"
      "--network=solviadev_default"
    ];
  };

  systemd.services."docker-solviadev-web" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-solviadev_default.service"
    ];
    requires = [
      "docker-network-solviadev_default.service"
    ];
    partOf = [
      "docker-compose-solviadev-root.target"
    ];
    wantedBy = [
      "docker-compose-solviadev-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-solviadev_default" = {
    path = [pkgs.docker];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f solviadev_default";
    };
    script = ''
      docker network inspect solviadev_default || docker network create solviadev_default
    '';
    partOf = ["docker-compose-solviadev-root.target"];
    wantedBy = ["docker-compose-solviadev-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-solviadev-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
